"""add_tags_trade_id_pnl_snapshot_to_journal_notes

Revision ID: 50e9415472ed
Revises: b65b14a8524f
Create Date: 2026-08-27 18:44:16.988026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e9415472ed'
down_revision: Union[str, Sequence[str], None] = 'b65b14a8524f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('trade_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pnl_snapshot', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_journal_notes_trade_id_orders', 'orders', ['trade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_notes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_journal_notes_trade_id_orders', type_='foreignkey')
        batch_op.drop_column('pnl_snapshot')
        batch_op.drop_column('trade_id')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
