"""add_options_fields

Revision ID: 563a88f9fa9c
Revises: 6d49cd1a11fd
Create Date: 2026-08-27 00:15:02.845529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563a88f9fa9c'
down_revision: Union[str, Sequence[str], None] = '6d49cd1a11fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_type', sa.Enum('equity', 'option', name='instrumenttype'), server_default='equity', nullable=False))
        batch_op.add_column(sa.Column('underlying', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('strike', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('expiry', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('option_type', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('lot_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('multiplier', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('multiplier')
        batch_op.drop_column('lot_size')
        batch_op.drop_column('option_type')
        batch_op.drop_column('expiry')
        batch_op.drop_column('strike')
        batch_op.drop_column('underlying')
        batch_op.drop_column('instrument_type')

    # ### end Alembic commands ###
