"""add_options_fields

Revision ID: 563a88f9fa9c
Revises: 6d49cd1a11fd
Create Date: 2026-08-27 00:15:02.845529

Adjusted by hand for a real reason, same as fe46ca828019: `op.add_column`
with a `sa.Enum(..., name='instrumenttype')` value was auto-generated
against a local SQLite dev DB, where this is harmless (batch mode rebuilds
the column with no named type involved at all). Against Postgres, this is
a DIFFERENT and more direct problem than fe46ca828019's enum-WIDENING
case: `instrumenttype` has never existed in the target database before
this migration -- and `op.add_column` on an EXISTING table does NOT
automatically emit `CREATE TYPE` first the way `op.create_table` does
(the postgresql ENUM type's auto-create hook is wired to a table-CREATE
event, not a column-ADD one; confirmed via SQLAlchemy's own
dialects/postgresql/named_types.py `_on_table_create`, and matches
Alembic's own documented behavior -- see alembic/sqlalchemy issue #488
and the standard `postgresql.ENUM(...).create(bind, checkfirst=True)`
workaround). Left as originally autogenerated, this add_column would fail
outright on Postgres with `type "instrumenttype" does not exist`. Fixed
by creating the type explicitly first, Postgres-only; SQLite's original
autogenerated path is unchanged.
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '563a88f9fa9c'
down_revision: Union[str, Sequence[str], None] = '6d49cd1a11fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

INSTRUMENT_TYPE_ENUM = postgresql.ENUM('equity', 'option', name='instrumenttype')


def _is_postgres() -> bool:
    return context.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    if _is_postgres():
        # checkfirst=True, not because a fresh deploy could already have
        # it (it can't -- this is the first migration that ever
        # references 'instrumenttype'), but so re-running this migration
        # after a partial failure doesn't itself crash on "already exists".
        INSTRUMENT_TYPE_ENUM.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_type', sa.Enum('equity', 'option', name='instrumenttype'), server_default='equity', nullable=False))
        batch_op.add_column(sa.Column('underlying', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('strike', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('expiry', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('option_type', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('lot_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('multiplier', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('multiplier')
        batch_op.drop_column('lot_size')
        batch_op.drop_column('option_type')
        batch_op.drop_column('expiry')
        batch_op.drop_column('strike')
        batch_op.drop_column('underlying')
        batch_op.drop_column('instrument_type')

    # ### end Alembic commands ###

    if _is_postgres():
        # The column is gone, but the named TYPE isn't dropped along with
        # it (same reason a column drop never implies a type drop on
        # SQLite either -- these are independent objects) -- without
        # this, re-running upgrade() after a downgrade would hit
        # checkfirst=True's own "already exists" no-op, which is fine,
        # but leaving an orphaned unused type behind on every downgrade
        # is exactly the kind of small drift this project's own
        # discipline (see accounting.py's docstring) argues against.
        INSTRUMENT_TYPE_ENUM.drop(op.get_bind(), checkfirst=True)
