"""add strategy_backtests

Revision ID: 691c4f110595
Revises: f263633ceb2a
Create Date: 2026-08-26 22:10:39.318844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691c4f110595'
down_revision: Union[str, Sequence[str], None] = 'f263633ceb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_key', sa.String(length=64), nullable=False),
    sa.Column('n_paths', sa.Integer(), nullable=False),
    sa.Column('n_bars', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('sharpe_median', sa.Float(), nullable=False),
    sa.Column('sharpe_ci_low', sa.Float(), nullable=False),
    sa.Column('sharpe_ci_high', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_backtests_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_backtests_strategy_key'), ['strategy_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_backtests_strategy_key'))
        batch_op.drop_index(batch_op.f('ix_strategy_backtests_generated_at'))

    op.drop_table('strategy_backtests')
    # ### end Alembic commands ###
