"""add risk settings, sub accounts, and algo execution tables

Revision ID: 6d49cd1a11fd
Revises: 691c4f110595
Create Date: 2026-08-26 22:45:36.659092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d49cd1a11fd'
down_revision: Union[str, Sequence[str], None] = '691c4f110595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('algo', sa.Enum('twap', 'vwap', name='sliceralgo'), nullable=False),
    sa.Column('horizon_bars', sa.Integer(), nullable=False),
    sa.Column('start_bar', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='parentorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parent_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_orders_user_id'), ['user_id'], unique=False)

    op.create_table('risk_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_order_qty', sa.Integer(), nullable=False),
    sa.Column('kelly_multiplier', sa.Float(), nullable=False),
    sa.Column('max_position_fraction', sa.Float(), nullable=False),
    sa.Column('daily_max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('pairs_entry_z', sa.Float(), nullable=False),
    sa.Column('pairs_exit_z', sa.Float(), nullable=False),
    sa.Column('pairs_stop_z', sa.Float(), nullable=False),
    sa.Column('coint_pvalue_max', sa.Float(), nullable=False),
    sa.Column('trading_halted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('sub_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('sizing_multiplier', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_accounts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sub_account_id', sa.Integer(), nullable=True))
        # Explicit names, not None: SQLite's batch mode recreates the table
        # to add a foreign key, and needs a real constraint name to do that
        # -- autogenerate emits None here (Base has no naming_convention
        # configured), which parses fine but raises "Constraint must have a
        # name" the moment this migration actually RUNS. Caught by
        # tests/test_migrations.py, not by eyeballing the generated file.
        batch_op.create_foreign_key('fk_orders_sub_account_id_sub_accounts', 'sub_accounts', ['sub_account_id'], ['id'])
        batch_op.create_foreign_key('fk_orders_parent_order_id_parent_orders', 'parent_orders', ['parent_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_parent_order_id_parent_orders', type_='foreignkey')
        batch_op.drop_constraint('fk_orders_sub_account_id_sub_accounts', type_='foreignkey')
        batch_op.drop_column('sub_account_id')
        batch_op.drop_column('parent_order_id')

    with op.batch_alter_table('sub_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_accounts_user_id'))

    op.drop_table('sub_accounts')
    op.drop_table('risk_settings')
    with op.batch_alter_table('parent_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_parent_orders_status'))
        batch_op.drop_index(batch_op.f('ix_parent_orders_created_at'))

    op.drop_table('parent_orders')
    # ### end Alembic commands ###
