"""make_backtest_ratio_columns_nullable

Revision ID: 955984befed9
Revises: 563a88f9fa9c
Create Date: 2026-08-27 03:05:18.113971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955984befed9'
down_revision: Union[str, Sequence[str], None] = '563a88f9fa9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_backtests', schema=None) as batch_op:
        batch_op.alter_column('sharpe_median',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sharpe_ci_low',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sharpe_ci_high',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('calmar_ratio',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_backtests', schema=None) as batch_op:
        batch_op.alter_column('calmar_ratio',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sharpe_ci_high',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sharpe_ci_low',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sharpe_median',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
