"""baseline: existing 7-table schema

Revision ID: b42793930f94
Revises: 
Create Date: 2026-08-26 19:27:07.374957

This reproduces the schema that `Base.metadata.create_all` had been building
implicitly at app startup, so a database can now be built from nothing by
migration alone.

An existing algoterminal.db already HAS these tables and must not have them
recreated -- mark it as already at this revision instead of upgrading it:

    .venv/bin/alembic stamp b42793930f94

A fresh database (new clone, CI, new deployment) instead runs:

    .venv/bin/alembic upgrade head

Note this revision was autogenerated against an EMPTY database on purpose.
Autogenerating it against the existing algoterminal.db produced an entirely
empty migration, because Alembic diffs the metadata against whatever the
target database already contains -- which would have left the project with a
baseline incapable of ever creating the schema it is supposed to define.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42793930f94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('journal_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_notes_user_id'), ['user_id'], unique=False)

    op.create_table('live_broker_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('encrypted_api_key', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_api_secret', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('paper', 'live', name='mode'), nullable=False),
    sa.Column('strategy_key', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='side'), nullable=False),
    sa.Column('order_type', sa.Enum('limit', 'market', name='ordertype'), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('px', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending_confirmation', 'submitted', 'filled', 'partially_filled', 'rejected', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('avg_fill_px', sa.Float(), nullable=True),
    sa.Column('engine_order_id', sa.Integer(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=128), nullable=True),
    sa.Column('entry_zscore', sa.Float(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('strategy_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_key', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.Enum('paper', 'live', name='mode'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_allocations_strategy_key'), ['strategy_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_allocations_user_id'), ['user_id'], unique=False)

    op.create_table('brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('paper', 'live', name='mode'), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('entry_side', sa.Enum('buy', 'sell', name='side'), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('stop_loss_px', sa.Float(), nullable=True),
    sa.Column('take_profit_px', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'triggered', 'cancelled', name='bracketstatus'), nullable=False),
    sa.Column('entry_order_id', sa.Integer(), nullable=False),
    sa.Column('closing_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closing_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['entry_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brackets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brackets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_brackets_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_brackets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brackets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brackets_user_id'))
        batch_op.drop_index(batch_op.f('ix_brackets_symbol'))
        batch_op.drop_index(batch_op.f('ix_brackets_status'))

    op.drop_table('brackets')
    with op.batch_alter_table('strategy_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_allocations_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_allocations_strategy_key'))

    op.drop_table('strategy_allocations')
    op.drop_table('paper_accounts')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_mode'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    op.drop_table('live_broker_credentials')
    with op.batch_alter_table('journal_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_journal_notes_created_at'))

    op.drop_table('journal_notes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
