"""add_n_valid_paths_split_trade_counts_on_strategy_backtests

Revision ID: b65b14a8524f
Revises: 955984befed9
Create Date: 2026-08-27 13:53:35.693164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65b14a8524f'
down_revision: Union[str, Sequence[str], None] = '955984befed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Existing rows in strategy_backtests were computed before the A2 fix to
    BARS_PER_YEAR (app.backtest.engine) -- they annualized as if one bar
    were one trading day when a bar is actually one simulated second, so
    every sharpe/calmar value already in this table is wrong by the ~23,400x
    scale factor that bug introduced. They are also missing the data this
    migration adds (there is no way to retroactively split a stale
    total_trades into orders_submitted/round_trips_closed). Cleared here
    rather than migrated forward, so the table only ever holds
    post-A2-fix, self-consistent rows -- scripts/run_backtests.py
    regenerates it. This also lets n_valid_paths/orders_submitted/
    round_trips_closed be added NOT NULL with no server_default: the table
    is empty for the rest of this migration's batch-recreate step.
    """
    op.execute("DELETE FROM strategy_backtests")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_backtests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_valid_paths', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('orders_submitted', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('round_trips_closed', sa.Integer(), nullable=False))
        batch_op.drop_column('total_trades')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_backtests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_trades', sa.INTEGER(), nullable=False, server_default='0'))
        batch_op.drop_column('round_trips_closed')
        batch_op.drop_column('orders_submitted')
        batch_op.drop_column('n_valid_paths')

    # ### end Alembic commands ###
