"""add stop_limit order type and stop_px column

Revision ID: f263633ceb2a
Revises: b42793930f94
Create Date: 2026-08-26 19:53:59.167701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f263633ceb2a'
down_revision: Union[str, Sequence[str], None] = 'b42793930f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_px', sa.Float(), nullable=True))
        batch_op.alter_column('order_type',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('limit', 'market', 'stop_limit', name='ordertype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_type',
               existing_type=sa.Enum('limit', 'market', 'stop_limit', name='ordertype'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('stop_px')

    # ### end Alembic commands ###
