"""add angelone client_code and totp_secret to live_broker_credentials

Revision ID: fe46ca828019
Revises: 50e9415472ed
Create Date: 2026-08-28 19:58:56.877982

NOT run as originally autogenerated -- adjusted by hand for a real reason,
not style. Autogenerate computed this diff against a local SQLite dev DB,
where every enum column is really just VARCHAR + a CHECK constraint (see
existing_type=sa.VARCHAR(length=5) in the original output). That's correct
for SQLite (batch mode rebuilds the whole table/column from scratch either
way) but WRONG once DATABASE_URL points at Postgres (app/db.py): there,
`mode` is a real, named, shared native ENUM type (created once in the
b42793930f94 baseline migration and reused by orders/strategy_allocations/
brackets alike) -- generic `alter_column(type_=sa.Enum(...))` calls have no
defined way to WIDEN an existing named Postgres enum's value set, and would
either fail outright or attempt to recreate a type that already exists.
Postgres has a purpose-built, unambiguous command for exactly this
operation instead: `ALTER TYPE mode ADD VALUE IF NOT EXISTS 'virtual'`
(stable since Postgres 9.3, and usable inside a normal transactional
migration since Postgres 12 -- both well below anything a current Render-
managed Postgres offering would run). SQLite keeps the original
autogenerated batch_alter_table path below unchanged, since that one WAS
verified directly (`alembic upgrade head` against a real local sqlite db).
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe46ca828019'
down_revision: Union[str, Sequence[str], None] = '50e9415472ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _is_postgres() -> bool:
    return context.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    if _is_postgres():
        # One ADD VALUE per new label -- Postgres only supports adding a
        # single value per ALTER TYPE statement, not a batch of them.
        op.execute("ALTER TYPE mode ADD VALUE IF NOT EXISTS 'virtual'")
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('brackets', schema=None) as batch_op:
            batch_op.alter_column('mode',
                   existing_type=sa.VARCHAR(length=5),
                   type_=sa.Enum('paper', 'virtual', 'live', name='mode'),
                   existing_nullable=False)

        with op.batch_alter_table('orders', schema=None) as batch_op:
            batch_op.alter_column('mode',
                   existing_type=sa.VARCHAR(length=5),
                   type_=sa.Enum('paper', 'virtual', 'live', name='mode'),
                   existing_nullable=False)

        with op.batch_alter_table('strategy_allocations', schema=None) as batch_op:
            batch_op.alter_column('mode',
                   existing_type=sa.VARCHAR(length=5),
                   type_=sa.Enum('paper', 'virtual', 'live', name='mode'),
                   existing_nullable=False)
        # ### end Alembic commands ###

    with op.batch_alter_table('live_broker_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_client_code', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_totp_secret', sa.LargeBinary(), nullable=True))


def downgrade() -> None:
    if _is_postgres():
        # Postgres has no DROP VALUE for an enum type -- removing a value
        # that might already be in use by real rows isn't a safe, generic
        # operation to auto-generate (unlike SQLite's batch rebuild, which
        # can only succeed here if nothing actually uses 'virtual' yet).
        # A real downgrade needs a human decision about what happens to
        # any row already tagged mode='virtual', not a silent guess.
        raise NotImplementedError(
            "Downgrading fe46ca828019 on Postgres is not automated -- Postgres has no "
            "ALTER TYPE ... DROP VALUE. Decide by hand what should happen to any row "
            "already tagged mode='virtual' before reversing this migration."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_allocations', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.Enum('paper', 'virtual', 'live', name='mode'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.Enum('paper', 'virtual', 'live', name='mode'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('live_broker_credentials', schema=None) as batch_op:
        batch_op.drop_column('encrypted_totp_secret')
        batch_op.drop_column('encrypted_client_code')

    with op.batch_alter_table('brackets', schema=None) as batch_op:
        batch_op.alter_column('mode',
               existing_type=sa.Enum('paper', 'virtual', 'live', name='mode'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
